services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Cuatrovientos25!
      MYSQL_DATABASE: db_products
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    image: anderfrago/iaw-ev3-products-backend:latest
    restart: always
    ports:
      - "8000:80"
    environment:
      DATABASE_URL: "mysql://root:Cuatrovientos25!@db:3306/db_products?serverVersion=8.0.32&charset=utf8mb4"
      APP_ENV: dev
      APP_SECRET: ca252f8a108c77f9c2a25eaed2e83ba5
      CORS_ALLOW_ORIGIN: "https?://localhost:4200"
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    image: anderfrago/iaw-ev3-products-frontend:latest
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
